import Image from "next/image";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import crypto from "crypto";

export const metadata: Metadata = {
  title: "Error-404",
  description: "Generated by create next app",
};

const authCookieSecret = process.env.AUTH_COOKIE_SECRET || "dev-secret";

const Error = async () => {
  const store = await cookies();
  const userIdRaw = store.get("userId")?.value;
  const roleRaw = store.get("userRole")?.value ?? "";
  const sig = store.get("userSig")?.value;

  let role: string | null = null;

  if (userIdRaw && roleRaw && sig) {
    const baseValue = `${userIdRaw}:${roleRaw}`;
    const expected = crypto
      .createHmac("sha256", authCookieSecret)
      .update(baseValue)
      .digest("hex");

    if (sig === expected && Number.isFinite(Number(userIdRaw))) {
      role = roleRaw;
    }
  }

  let href = "/auth/login";
  if (role === "admin") {
    href = "/admin/";
  } else if (role) {
    href = "/user";
  }

  return (
    <>
      <div className="h-screen flex items-center justify-center bg-background">
        <div className="text-center">
          <Image
            src={"/images/backgrounds/errorimg.svg"}
            alt="error"
            className="mb-4"
            width={400}
            height={300}
          />
          <h1 className="text-ld text-4xl mb-6">Opps!!!</h1>
          <h6 className="text-xl text-ld">
            This page you are looking for could not be found.
          </h6>
          <Button asChild className="mt-6 mx-auto">
            <Link href={href}>Go Back</Link>
          </Button>
        </div>
      </div>
    </>
  );
};

export default Error;
